# Generated by Django 3.1.3 on 2020-11-28 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Proprietario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True)),
                ('phone', models.CharField(max_length=200, null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('date_create', models.DateField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('especie', models.CharField(max_length=30)),
                ('raca', models.CharField(max_length=30)),
                ('peso', models.FloatField()),
                ('idade', models.IntegerField()),
                ('nasc', models.CharField(max_length=20)),
                ('sexo', models.CharField(max_length=1)),
                ('porte', models.CharField(max_length=30)),
                ('obs', models.TextField()),
                ('proprietario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pet.proprietario')),
            ],
        ),
    ]
