# Generated by Django 3.1.3 on 2020-11-28 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proprietario',
            name='user',
        ),
    ]
