# Generated by Django 3.1.3 on 2020-11-28 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0002_remove_proprietario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='nasc',
            field=models.DateField(),
        ),
    ]
