# Generated by Django 3.1.3 on 2020-11-29 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0004_consulta_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='proprietario',
        ),
        migrations.AddField(
            model_name='pet',
            name='prop',
            field=models.ManyToManyField(to='pet.Proprietario'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='obs',
            field=models.TextField(blank=True, null=True),
        ),
    ]
