# Generated by Django 3.1.3 on 2020-11-29 05:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0005_auto_20201129_0500'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consulta',
            name='proprietario',
        ),
    ]
