# Generated by Django 3.1.7 on 2021-03-04 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0007_auto_20210304_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='services',
            field=models.ManyToManyField(to='pet.Service'),
        ),
    ]
