# Generated by Django 3.1.7 on 2021-03-11 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0008_pet_services'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='idade',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='nasc',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='peso',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='porte',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='services',
            field=models.ManyToManyField(blank=True, to='pet.Service'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sexo',
            field=models.CharField(max_length=1, null=True),
        ),
    ]
