# Generated by Django 3.1.7 on 2021-04-03 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pet', '0009_auto_20210311_2315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='proprietario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pet.proprietario'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='services',
            field=models.ManyToManyField(blank=True, null=True, to='pet.Service'),
        ),
    ]
